
services:
  auth-service:
    build: .
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET_FILE=/run/secrets/JWT_SECRET
      - JWT_EXPIRES_IN=1h
      - MONGO_URL_FILE=/run/secrets/MONGO_URL  # Update this path to your secrets
    depends_on:
      - mongo
    networks:
      - auth-network
      - shared-network
    secrets:
      - JWT_SECRET
      - MONGO_URL
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - '27018:27017'  # Standard MongoDB port for non-replicated setups
    restart: unless-stopped
    networks:
      - auth-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}  # Environment variable for MongoDB root username
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}  # Environment variable for MongoDB root password
    healthcheck:
      test: ['CMD', 'mongosh', 'admin', '--eval', "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 2s
      retries: 20

secrets:
  JWT_SECRET:
    file: ./secrets/JWT_SECRET.txt
  MONGO_URL:
    file: ./secrets/MONGO_URL.txt  # Path for the MongoDB URL secret

volumes:
  mongo-data:

networks:
  auth-network:
    driver: bridge
  shared-network:
    driver: bridge
